FROM jenkins/inbound-agent:latest-jdk17

USER root

RUN apt-get update && apt-get install -y \
    curl \
    jq \
    unzip \
    gnupg \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*


RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash


RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
       > /etc/apt/sources.list.d/hashicorp.list \
    && apt-get update && apt-get install -y terraform \
    && rm -rf /var/lib/apt/lists/*

USER jenkins
